### ISSUE TITLE
Allow a way to attach that doesn't modify listen or adds .server?

### ISSUE THREAD

**Issue by laggingreflex** [mattstyles/koa-socket#12]
I have a custom Koa wrapper extending from the original Koa class and I'm over-riding the listen function with my own, and also attaching a custom `app.server`. 

Koa-socket doing both of those things as well interferes with my wrapper. 

Would it be possible to have other ways to attach to app without modifying internals as such, like providing a way to just take `app.callback()` or `server`?

**Comment by laggingreflex** [comment]
How about checking to see if `app.server` already exists, and only creating one if it doesn't? [pr](https://github.com/mattstyles/koa-socket/pull/13)

**Comment by mattstyles** [comment]
Yep, I agree, and the PR looks good to me.

**Comment by mattstyles** [comment]
All published as 4.1.0
