### ISSUE TITLE
Support Node.js 0.12.7

### ISSUE THREAD

**Issue by vjpr** [mattstyles/koa-socket#6]
Node 4 is quite new, I think the module should be compiled with Babel to 0.12.7. The `class` keyword is breaking for me.

**Comment by mattstyles** [comment]
I'm curious, is there a usecase for *not* updating to node 4?

I know there is pain updating large infrastructure but I thought node 4 was largely an uneventful leap from 0.12.x

**Comment by vjpr** [comment]
I tried once before and ran into some issues with some native binaries not supporting Node 4. This is the main issue.

**Comment by mattstyles** [comment]
I'm not really keen on transpilation just for older versions of node.
