### ISSUE TITLE
Namespaces don't have a broadcast method

### ISSUE THREAD

**Issue by TMiguelT** [mattstyles/koa-socket#7]
Contrary to the example code, this doesn't actually work:

```javascript
const IO = require('koa-socket');
const app = require('koa')();
const chat = new IO({
  namespace: 'chat'
})
 
chat.attach( app )
 
app.chat.broadcast('event')
```

`app.chat.broadcast is not a function`

**Comment by mattstyles** [comment]
This should be fixed with this [commit](https://github.com/mattstyles/koa-socket/commit/592c6e3da722d95bfb03c6d8427079565cda9e01).
